
* Table of contents                               :toc_4:noexport:
- [[#ice-sheet-freshwater-forcing][Ice Sheet Freshwater Forcing]]
  - [[#introduction][Introduction]]
  - [[#workshop][Workshop]]
  - [[#data-products][Data Products]]
    - [[#antarctic][Antarctic]]
      - [[#iceberg-melt][Iceberg melt]]
      - [[#ice-shelf-melt][Ice shelf melt]]
      - [[#surface-runoff][Surface runoff]]
      - [[#basal-grounded-runoff][Basal (grounded) runoff]]
    - [[#greenland][Greenland]]
      - [[#surface-runoff-1][Surface runoff]]
      - [[#basal-runoff][Basal runoff]]
      - [[#glacier-termini][Glacier termini]]
      - [[#iceberg-melt-locations][Iceberg melt locations]]
    - [[#unused][Unused]]
      - [[#antarctic-iceberg-days][Antarctic Iceberg Days]]

* Ice Sheet Freshwater Forcing

** Introduction

This repository contains discussions and workbooks (code) from a virtual workshop on Anomalous Freshwater Fluxes.

Included in this repository are:
+ GitHub [[https://github.com/NASA-GISS/freshwater-forcing-workshop/discussions][Discussions]] from before, during, and after the workshop.
+ Workbooks (code) used to build data products (e.g. Greenlandic and Antarctic freshwater from surface melt, ice shelf melt, basal melt, icebergs, etc.).
+ Examples of data product post-processing to aid modelers who want use the data.

** Workshop

The virtual workshop on Anomalous Freshwater Fluxes aimed to capture freshwater fluxes from ice sheets and ice shelves for use in climate models that don't include interactive ice sheets. The workshop slides, videos, and discussion notes are archived at https://zenodo.org/doi/10.5281/zenodo.11127902.
 
To stay up-to-date with existing and new discussions, click on the =watch= button near the top of this page and then select =All Activity= or =Custom > Discussions (and Issues)=. If you're new to GitHub, it can be used as a collaborative project management tool (in addition to a code repository). See Braga (2023) http://doi.org/10.1111/2041-210x.14108.

** Data Products

*** Antarctic

**** Iceberg melt

**** Ice shelf melt
**** Surface runoff
**** Basal (grounded) runoff

*** Greenland

**** Surface runoff

This data product is MAR runoff distributed by Rignot (IMBIE) region, but processed at stream level by Mankoff (2020) http://doi.org/10.5194/essd-12-2811-2020. The data includes 'ice runoff' which comes from melted ice, snow, and rain on the ice sheet, and 'land runoff' which comes from melted snow and rain on land. Runoff is routed through individual streams (subglacial for ice, sub-aerial for land). Both ice-sourced and land-sourced runoff can enter the ocean either at the surface (from a terrestrial stream) or at depth subglacially. This value is estimated per stream. When summing by ROI, the minimum submarine discharge depth is provided for each ROI.

+ Workbook: [[./greenland_runoff.org]]
+ Data product: =GL_runoff.nc=

**** Basal runoff

See Karlsson (2023) http://doi.org/10.34194/geusb.v53.8338 

**** Glacier termini

This product is generated from flux gates ~5 km upstream of the terminus.

It lacks:
+ Terminus retreat, which should add ~10 % over the last two decades
+ Splitting output between icebergs and submarine melt, which is ~50 % +- 40 %

+ Workbook: [[./greenland_discharge.org]]
+ Data product: =GL_discharge.nc=

***** Solid ice calving

To do

***** Submarine melt

To do

**** Iceberg melt locations

This dataset provides spatial maps of iceberg meltwater based on iceberg source. Maps are weighted masks where each region sums to one, plus one all-Greenland weighted map.

+ Workbook: [[./greenland_iceberg_melt.org]]
+ Data product: =GL_iceberg_melt_{3413,4326}.nc=


*** Basal runoff

This product splits basal melt from Karlsson (2021) http://doi.org/10.1038/s41467-021-23739-z into regions, with two products per region: Water that enters fjords at their surface from sub-aerial streams, and water that enters subglacially.

+ Workbook: [[./greenland_basal_melt.org]]
+ Data product: =GL_basal_melt_3413.nc=

** Unused
*** Antarctic Iceberg Days

This data product is not meltwater from icebergs, but instead days and locations where icebergs are observed. The raw data comes from Budge (2018) http://doi.org/10.1109/jstars.2017.2784186 and is then binned in (lon,lat) bins where the values shows the number of days icebergs spend in each in. 18 maps are generated, one per Rignot (IMBIE) basin, where icebergs are assigned to the basin nearest their first recorded location.

+ Workbook: [[./iceberg_days.org]]
+ Data product: =iceberg_days.nc=

